import { newsOne, newsTwo, newsThree } from "./images";

export const newsData = [
  {
    id: "1",
    title: "Studying in Canada",
    description:
      "The education section features articles on academic trends, policies, and updates from schools and univers...",
    category: "Education",
    author: "John Smith",
    date: "4 days ago",
    reads: 5,
    likes: 650,
    comments: 0,
    shares: 100,
    image: newsOne,
  },
  {
    id: "2",
    title: "Real Estate Trends in 2025",
    description:
      "The real estate market is shifting with new trends in urban development and sustainability...",
    category: "Real Estate",
    author: "Emily Carter",
    date: "3 days ago",
    reads: 8,
    likes: 890,
    comments: 12,
    shares: 75,
    image: newsTwo,
  },
  {
    id: "3",
    title: "Breakthrough in AI Technology",
    description:
      "Researchers have developed a new AI model that surpasses human capabilities in problem-solving...",
    category: "Technology",
    author: "Michael Johnson",
    date: "2 days ago",
    reads: 15,
    likes: 1200,
    comments: 45,
    shares: 200,
    image: newsThree,
  },
  {
    id: "4",
    title: "Climate Change and Its Impact",
    description:
      "Rising global temperatures continue to affect wildlife, agriculture, and coastal communities...",
    category: "Environment",
    author: "Sophia Martinez",
    date: "5 days ago",
    reads: 10,
    likes: 750,
    comments: 30,
    shares: 150,
    image: newsOne,
  },
  {
    id: "5",
    title: "Health Benefits of a Balanced Diet",
    description:
      "Experts emphasize the importance of a well-balanced diet in preventing chronic diseases...",
    category: "Health",
    author: "Daniel Lee",
    date: "6 days ago",
    reads: 7,
    likes: 500,
    comments: 18,
    shares: 80,
    image: newsTwo,
  },
  {
    id: "6",
    title: "The Rise of Electric Vehicles",
    description:
      "Automakers are accelerating their transition to electric vehicles, promising a greener future...",
    category: "Automobile",
    author: "Emma Wilson",
    date: "1 week ago",
    reads: 12,
    likes: 950,
    comments: 40,
    shares: 130,
    image: newsThree,
  },
  {
    id: "7",
    title: "Cryptocurrency Market Update",
    description:
      "Bitcoin and Ethereum prices see a surge as investors regain confidence in the market...",
    category: "Finance",
    author: "Oliver Brown",
    date: "8 days ago",
    reads: 20,
    likes: 1100,
    comments: 60,
    shares: 250,
    image: newsOne,
  },
  {
    id: "8",
    title: "SpaceX's Mission to Mars",
    description:
      "Elon Musk's SpaceX is preparing for its most ambitious Mars mission yet...",
    category: "Space",
    author: "Lucas Scott",
    date: "9 days ago",
    reads: 18,
    likes: 1400,
    comments: 55,
    shares: 300,
    image: newsTwo,
  },
  {
    id: "9",
    title: "The Future of Remote Work",
    description:
      "Companies are adapting to a hybrid work model as remote work becomes the new norm...",
    category: "Business",
    author: "Lily Adams",
    date: "10 days ago",
    reads: 14,
    likes: 860,
    comments: 35,
    shares: 120,
    image: newsThree,
  },
  {
    id: "10",
    title: "Advancements in Quantum Computing",
    description:
      "Tech companies are making significant strides in quantum computing research...",
    category: "Science",
    author: "Henry Thomas",
    date: "11 days ago",
    reads: 9,
    likes: 720,
    comments: 25,
    shares: 90,
    image: newsOne,
  },
];
